/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre;

import DAO.*;
import Mapping.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.JSType;
import java.time.LocalDate;

/**
 *
 * @author DIOUF ABBAS
 */
public class AddBon extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBon
     */
    public AddBon() {
        initComponents();
        try {
            DefaultComboBoxModel modele1 = new DefaultComboBoxModel(MatosBean.findAll().toArray());
            MatCBX.setModel(modele1);
            MatCBX.setSelectedIndex(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erreur" + ex.getMessage(), "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);
        }
        jLabel4.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nbTFD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MatCBX = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 153, 255));
        jTable1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matériel", "Quantité", "Prix unitaire", "Prix total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 425, 370));

        nbTFD.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        getContentPane().add(nbTFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 130, 30));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 107, 100, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Matériel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 70, 20));

        MatCBX.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        MatCBX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(MatCBX, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 130, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton2.setText("Valider Bon");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 200, 80));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 200, 80));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Prix Total Commande : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 200, 20));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 190, 20));
        getContentPane().add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
String dept[][] = null;
    ArrayList list = new ArrayList();
    detailsBon dep = null;
    String[] Colonne = new String[4];
    float f = 0;
    float prTot = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!JSType.isNumber(nbTFD.getText())) {
            JOptionPane.showMessageDialog(null, "Le nombre de materiel doit etre numérique", "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Colonne[0] = "Matériel";
        Colonne[1] = "Nombre";
        Colonne[2] = "Prix unitaire";
        Colonne[3] = "Prix total";
        detailsBon bc = new detailsBon();
        
        try {
            bc.setIdBnCmd(BonCmdBean.nbChmp() + 1);
            bc.setIdChefDept(Chef_Dept.getInstance().getId());
            Materiel mat = (Materiel) MatCBX.getSelectedItem();
            bc.setIdMat(mat.getId());
            bc.setQte(Float.parseFloat(nbTFD.getText()));
            list.add(bc);
            dep = new detailsBon();
            dept = new String[list.size()][4];
            int i = 0;
            for (Object list1 : list) {
                dep = (detailsBon) list1;
                Materiel mate = MatosBean.rechById(dep.getIdMat());
                dept[i][0] = mate.getNom();
                dept[i][1] = dep.getQte() + "";
                dept[i][2] = mate.getPrix() + "";
               f = (mate.getPrix() * dep.getQte());
                dept[i][3] = f + "";
                prTot = prTot + f;
                jLabel4.setText(prTot + "FCFA");
                i++;
            }
            jTable1.setModel(new DefaultTableModel(dept, Colonne));
            nbTFD.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erreur" + ex.getMessage(), "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getModel()==null)
        {
        JOptionPane.showMessageDialog(null, "veuillez ajouter un materiel", "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        detailsBon dep = new detailsBon();
        BonCommande bc = new BonCommande();
        int a =0;
        
        try {
            bc.setDatecmd(java.sql.Date.valueOf(LocalDate.now()));
            bc.setPrix(prTot);
            bc.setEtat(0);
            int b =  BonCmdBean.addBon(bc);
            for (Object list1 : list) {
                dep = (detailsBon) list1;
                a = DetailsBonBean.addDetBon(dep);
            }
            
 
          if(b!=0)
              JOptionPane.showMessageDialog(null, "Commande ajouté", "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);
          this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erreur" + ex.getMessage(), "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MatCBX;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nbTFD;
    // End of variables declaration//GEN-END:variables
}
